os: linux
dist: xenial
language: shell
script: true
before_install:
- openssl aes-256-cbc -K $encrypted_2f2a00660404_key -iv $encrypted_2f2a00660404_iv
  -in test_key.enc -out /tmp/test_key -d
- chmod 600 /tmp/test_key
- eval $(ssh-agent)
- ssh-add /tmp/test_key